version: '2'

volumes:
  postgres_data: {}
  postgres_backup: {}
  django_static: {}

services:
  postgres:
    build: ./compose/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    depends_on:
      - postgres
      - redis
    volumes:
      - django_static:/app/staticfiles
    command: /daphne.sh
    env_file: .env

  worker:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    depends_on:
      - django
    env_file: .env
    command: python manage.py runworker --exclude-channels=follow


  game_worker:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    depends_on:
      - django
    env_file: .env
    command: python manage.py runworker --only-channels=follow

  delay_worker:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    user: django
    depends_on:
      - django
    env_file: .env
    command: python manage.py rundelay

  redis:
    image: redis:latest

  nginx:
    build: ./compose/nginx
    depends_on:
      - django
    ports:
      - "0.0.0.0:80:80"
    volumes:
      - django_static:/static