# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 06:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('interactive', '0001_initial'), ('interactive', '0002_auto_20160924_2245'), ('interactive', '0003_auto_20160924_2245'), ('interactive', '0004_auto_20160925_0129'), ('interactive', '0005_auto_20160925_0132'), ('interactive', '0006_auto_20160925_0201'), ('interactive', '0007_auto_20160925_0204'), ('interactive', '0008_auto_20160925_0207'), ('interactive', '0009_auto_20160925_0210'), ('interactive', '0010_auto_20160925_0213'), ('interactive', '0011_interactive_channel')]

    initial = True

    dependencies = [
        ('round', '0002_round_round_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interactive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_time', models.DateTimeField(null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InteractiveRound',
            fields=[
                ('round_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='round.Round')),
                ('influencers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            bases=('round.round',),
        ),
        migrations.AddField(
            model_name='interactive',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interactive',
            name='started',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_users', models.PositiveSmallIntegerField()),
                ('min_users', models.PositiveSmallIntegerField()),
                ('max_influencers', models.PositiveSmallIntegerField()),
                ('min_influencers', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='interactive',
            name='constraints',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactive.Settings'),
        ),
        migrations.AddField(
            model_name='interactive',
            name='channel',
            field=models.CharField(default='Helloworld', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
