# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 22:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('round', '0002_round_round_order'),
        ('interactive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundInteractive',
            fields=[
                ('round_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='round.Round')),
                ('influencers', models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('round.round',),
        ),
        migrations.AddField(
            model_name='interactive',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='interactive',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='interactive',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
