# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0001_squashed_0011_interactive_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactive',
            name='channel',
        ),
    ]
