# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 04:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0003_auto_20161003_1733'),
        ('interactive', '0003_auto_20161005_0418'),
    ]

    operations = [
    ]
