# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0003_auto_20161005_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactiveround',
            name='influenced_guess',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
