# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0003_auto_20160924_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactive',
            name='max_users',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='interactive',
            name='min_users',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='interactive',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
