# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0004_merge_20161005_0448'),
        ('interactive', '0004_interactiveround_influenced_guess'),
    ]

    operations = [
    ]
