# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 00:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0005_auto_20161006_2258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='max_influencers',
            new_name='max_following',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='min_influencers',
            new_name='min_following',
        ),
    ]
