# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0005_auto_20160925_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_users', models.PositiveSmallIntegerField()),
                ('min_users', models.PositiveSmallIntegerField()),
                ('max_influencers', models.PositiveSmallIntegerField()),
                ('min_influencers', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='interactive',
            name='max_users',
        ),
        migrations.RemoveField(
            model_name='interactive',
            name='min_users',
        ),
        migrations.AddField(
            model_name='interactive',
            name='constraints',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactive.Settings'),
            preserve_default=False,
        ),
    ]
