# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 01:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interactive', '0006_auto_20161007_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactiveround',
            name='following',
        ),
        migrations.AddField(
            model_name='interactiveround',
            name='following',
            field=models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
