# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 02:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0007_auto_20160925_0204'),
    ]

    operations = [
    ]
