# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 01:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0007_auto_20161007_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactiveround',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interactive.Interactive'),
        ),
    ]
