# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 02:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0008_interactiveround_game'),
        ('interactive', '0005_merge_20161005_1935'),
    ]

    operations = [
    ]
