# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0009_auto_20160925_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactive',
            name='constraints',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactive.Settings'),
        ),
    ]
