# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0009_interactiveround_outcome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interactiveround',
            name='followers',
        ),
    ]
