# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 04:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0009_merge_20161007_0202'),
        ('interactive', '0009_interactiveround_outcome'),
    ]

    operations = [
    ]
