# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0010_auto_20160925_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactive',
            name='channel',
            field=models.CharField(default='Helloworld', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
