# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0010_merge_20161012_0411'),
        ('interactive', '0010_remove_interactiveround_followers'),
    ]

    operations = [
    ]
