# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 00:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0011_merge_20161012_2314'),
        ('interactive', '0011_survey'),
    ]

    operations = [
    ]
