# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0012_merge_20161013_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactiveround',
            name='outcome',
            field=models.BooleanField(default=False),
        ),
    ]
