# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 19:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interactive', '0013_auto_20161013_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='user',
        ),
        migrations.AddField(
            model_name='survey',
            name='user',
            field=models.ManyToManyField(related_name='influenced_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
