# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0014_auto_20161013_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='user',
        ),
    ]
