# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0015_remove_survey_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
