# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0016_survey_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='alpha',
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
    ]
