# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 00:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0017_settings_alpha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='alpha',
            new_name='score_lambda',
        ),
    ]
