# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 01:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0018_auto_20161021_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='score_lambda',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
