# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 03:52
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0019_auto_20161021_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactiveround',
            name='influenced_guess',
            field=models.DecimalField(decimal_places=2, default=Decimal('NaN'), max_digits=3),
        ),
    ]
