# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-05 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0030_settings_max_rounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactive',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
