# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-02 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0031_auto_20161105_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='game',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='gender',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
