# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-17 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive', '0032_auto_20161202_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='bugs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='pay',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='game',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='gender',
            field=models.TextField(null=True),
        ),
    ]
