# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-07 01:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_static', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
                ('payload', models.TextField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactive_static.InteractiveStatic')),
            ],
        ),
        migrations.AddField(
            model_name='settings',
            name='kickout_seconds',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='settings',
            name='max_prompts',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='settings',
            name='minutes_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='settings',
            name='prompt_seconds',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='settings',
            name='prompt_sound_interval',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
