# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-09 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_user_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='game_type',
            field=models.CharField(max_length=10, verbose_name='User Type'),
        ),
    ]
