# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-02 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usertypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='kicked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='prompted',
            field=models.SmallIntegerField(default=0),
        ),
    ]
