# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-02 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_shocks', '0002_auto_20170301_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='minutes_mode',
            field=models.BooleanField(default=False),
        ),
    ]
