# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-02 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_shocks', '0003_settings_minutes_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='max_prompts',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
