# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-03 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_shocks', '0004_settings_max_prompts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
                ('payload', models.TextField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interactive_shocks.InteractiveShocks')),
            ],
        ),
    ]
