# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-03 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactive_shocks', '0005_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='prompt_sound_interval',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
