# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 04:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('round', '0001_initial'), ('round', '0002_round_round_order'), ('round', '0003_auto_20161005_0527'), ('round', '0004_auto_20161007_0849'), ('round', '0005_auto_20161012_0351'), ('round', '0006_auto_20161012_0355'), ('round', '0007_auto_20161012_0358')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot', models.URLField()),
                ('answer', models.DecimalField(decimal_places=3, max_digits=4)),
                ('duration', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess', models.DecimalField(decimal_places=2, max_digits=3)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='round.Plot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('round_order', models.PositiveSmallIntegerField(default=0)),
                ('end_time', models.DateTimeField(null=True)),
                ('start_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='plot',
            name='answer',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together=set([('user', 'round_order')]),
        ),
    ]
