# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0001_squashed_0007_auto_20161012_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='round_order',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
