# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='round_order',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
