# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 03:52
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0002_auto_20161012_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='guess',
            field=models.DecimalField(decimal_places=2, default=Decimal('NaN'), max_digits=3),
        ),
    ]
