# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0002_round_round_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plot',
            name='answer',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='round',
            name='guess',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
