# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-07 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0003_auto_20161005_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='start_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
