# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 03:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('round', '0006_auto_20161012_0355'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='round',
            unique_together=set([('user', 'round_order')]),
        ),
    ]
