# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0012_auto_20161024_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='batch',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
