# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 21:54
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('round', '0013_plot_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=4),
        ),
    ]
