# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-25 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='plot',
            field=models.URLField(),
        ),
    ]
