# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-25 22:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20160825_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='player',
        ),
    ]
