# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 21:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20160911_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
