# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_auto_20160912_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='score',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=8),
        ),
    ]
