# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_auto_20160912_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='exist_survey',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='control',
            name='instruction',
            field=models.BooleanField(default=False),
        ),
    ]
