# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0013_auto_20161101_0236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='control',
            name='constraints',
        ),
        migrations.RemoveField(
            model_name='control',
            name='score_lambda',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='score_lambda',
        ),
        migrations.AlterField(
            model_name='survey',
            name='game',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
