# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 04:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0014_auto_20161102_0257'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='batch_size',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='setting',
            name='batch_size',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
