# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0015_auto_20161102_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='bugs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='pay',
            field=models.TextField(null=True),
        ),
    ]
