# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-07 01:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0017_auto_20161105_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='types',
            field=models.CharField(default='', max_length=1000, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
