# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-07 18:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0018_setting_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='types',
            field=models.CharField(default='', help_text='a comma separated lists of integers from 0-2. 0 for easy, 1 for medium and 2 for hard', max_length=1000, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
